### PR TITLE
Volatile Write around Sequence field

### PR DESCRIPTION
**Pull request by alexandrnikitin**

### CODE REVIEW

**Comment by alexandrnikitin** [comment]
@lust4life, WDYT about this fix? When we just Volatile.Write around the `Sequence` field.

**Comment by lust4life** [comment]
```csharp

        [StructLayout(LayoutKind.Explicit, Size = 16, CharSet = CharSet.Ansi)]
        private struct Cell
        {
            [FieldOffset(0)]
            public int Sequence;
            [FieldOffset(8)]
            public object Element;
```

hi @alexandrnikitin , do we need this explicit structlayout in cell struct ? how about leave the compile generate for it (so it can be auto aligned)?

**Comment by alexandrnikitin** [comment]
Same reason as with `var buffer = _buffer;` in enqueue/dequeue. We always read `Sequence` first. If it's on the edge of a cache line, then hopefully prefetch can help with `Element`. But it's my speculation mostly, I don't have enough evidence. It's not visible in microbenchmarks as everything in L1 already.

When JIT alignes it puts `Element` first:

```
Type layout for 'CellAuto'
Size: 16 bytes. Paddings: 4 bytes (%25 of empty space)
|=================================|
|   0-7: Object Element (8 bytes) |
|---------------------------------|
|  8-11: Int32 Sequence (4 bytes) |
|---------------------------------|
| 12-15: padding (4 bytes)        |
|=================================|


Type layout for 'CellLayoutKindExplicit'
Size: 16 bytes. Paddings: 4 bytes (%25 of empty space)
|=================================|
|   0-3: Int32 Sequence (4 bytes) |
|---------------------------------|
|   4-7: padding (4 bytes)        |
|---------------------------------|
|  8-15: Object Element (8 bytes) |
|=================================|
```

**Comment by lust4life** [comment]
get it , thanks. 👍

**Pull request merged**
